/* * * * * * * * * *
 *   disTime .js   *
 *  Version   0.1  *
 *  License:  MIT  *
 * Simon  Waldherr *
 * * * * * * * * * */

/*jslint browser: true*/

eval(function(p,a,c,k,e,d){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p}('1X t(q,d,j){"1W 1V";1U u,z,n,i,w,y,a,b,h={\'1T\':[\'\',\' 1S\',\' 1R \',\' 1Q \',\' 1P \',\' 1O \',\' 1N \',\' 1M \',\' 1L \',\' 1K \',\' 1J \',\' 1I \',\' 1H \',\' 1G \',\' 1F \',\' 1E \',\' 1D \'],\'1C\':[\'1B \',\'\',\' 1A \',\' 1z \',\' 1y \',\' 1x \',\' 1w \',\' 1v \',\' 1u \',\' 1t \',\' 1s \',\' 1r \',\' 1q \',\' 1p \',\' 1o \',\' 1n \',\' 1m \'],\'1l\':[\'\',\' 1k\',\' e \',\' 1j \',\' 1i \',\' 1h \',\' 1g \',\' 1f \',\' 1e \',\' 1d \',\' 1c \',\' 1b \',\' 1a \',\' 19 \',\' 18 \',\' 17 \',\' Z \']};w=c(Y.X()/B,10)+q;u=W.V(\'a\');z=u.U;n=w;T(i=0;i<z;++i){y=u[i].S("R-Q");a=w-y;f((P(a)===\'O\')&&(c(a,10)===a)){b=h[d][0];f(a>s){b+=c(c(a,10)/c(s,10),10);f(c(a/s*1.2,10)===1){b+=h[d][15]}l{b+=h[d][16]}}f(((a<g*g*p*x)&&(a>g*g*p*7*4))||((a>g*g*p*x)&&(j)&&(c(a%s/m,10)!==0))){b+=c(a%s/m,10);f(c(a%s/m,10)===1){b+=h[d][13]}l{b+=h[d][14]}f(((a<g*g*p*x)&&(j)&&(c(a%m/k,10)!==0))){b+=c(a%m/k,10);f(c(a%m/k,10)===1){b+=h[d][9]}l{b+=h[d][10]}}}f(((a<g*g*p*7*4)&&(a>g*g*p*7))||((a<N)&&(a>M)&&(j)&&(c(a%L/m,10)!==0))){b+=c(a%m/r,10);f(c(a%m/r,10)===1){b+=h[d][11]}l{b+=h[d][12]}}f(((a<g*g*p*7)&&(a>E))||((a<m)&&(a>K)&&(j)&&(c(a%r/k,10)!==0))){b+=c(a%r/k,10);f(c(a%r/k,10)===1){b+=h[d][9]}l{b+=h[d][10]}}f(((a<k)&&(a>D))||((a<r)&&(a>E)&&(j)&&(c(a%k/o,10)!==0))){b+=c(a%k/o,10);f(c(a%k/o,10)===1){b+=h[d][7]}l{b+=h[d][8]}}f(((a<o)&&(a>C))||((a<k)&&(a>D)&&(j)&&(c(a%o/g,10)!==0))){b+=c(a%o/g,10);f(c(a%o/g,10)===1){b+=h[d][5]}l{b+=h[d][6]}}f((a<g)||((a<o)&&(a>C)&&(j)&&(a%g!==0))){b+=a%g;f(a%g===1){b+=h[d][3]}l{b+=h[d][4]}}b+=h[d][1];u[i].J=b;f(a<n){n=a}}}f((n<I)||(j&&n<A)){v(t,B,q,d,j)}l f((n<A)||(j&&n<k)){v(t,H,q,d,j)}l f((n<k)||(j)){v(t,G,q,d,j)}l{v(t,F,q,d,j)}}',62,122,'||||||||||distime|insert|parseInt|language||if|60|words||detailed|86400|else|2419200|smallest|3600|24|timedifference|604800|31536000|disTime|elements|setTimeout|timestamp|365|elementtime|elementcount|3601|1000|59|3599|86399|86400001|3600001|60000|61|innerHTML|604799|2592000|2419199|10368000|number|typeof|time|data|getAttribute|for|length|getElementsByClassName|document|now|Date|anni||||||||anno|mesi|mese|settimane|settimana|giorni|giorno|ore|ora|minuti|minuto|secondi|secondo|fa|it|Jahre|Jahr|Monate|Monat|Wochen|Woche|Tage|Tag|Stunden|Stunde|Minuten|Minute|Sekunden|Sekunde|und|vor|de|years|year|months|month|weeks|week|days|day|hours|hour|minutes|minute|seconds|second|and|ago|en|var|strict|use|function'.split('|')));
